@startuml DriveHub

' El diagrama de clases es orientativo, podra sufrir cambios a medida que avance el proyecto.

title Diagrama de Clases - DriveHub


interface ITemporada{
    calculoPorTemporada(sistema: SistemaDriveHub): number; 
}

class temporada_alta implements ITemporada
class temporada_baja implements ITemporada
class temporada_media implements ITemporada     

interface INecesitaMantenimiento{
    + necesitaMantenimiento():boolean
}

class cantViajes implements INecesitaMantenimiento
class kilometrosParaMantenimiento implements INecesitaMantenimiento
class ultimoMantenimeinto implements INecesitaMantenimiento

interface IEstadoVehiculo {
    + asignarAlquiler() : void
    + asignarDisponible() : void
    + asignarMantenimiento() : void
    + asignarLimpieza() : void

    + puedeAlquilar() : boolean
    + estaEnMantenimiento() : boolean 
}

interface IGeneradorDeReporte {
    + vehiculoMasAlquilado(fechaInicio: Date, fechaFin: Date, reserva: Reserva[]): Vehiculo
    + vehiculoMenosAlquilado(fechaInicio: Date, fechaFin: Date, reserva: Reserva[]): Vehiculo
    + vehiculoMasRentable(vehiculos: Map<Vehiculo, number>): Vehiculo
    + vehiculoMenosRentable(vehiculos: Map<Vehiculo, number>): Vehiculo
    + vehiculosOcupados(fechaBusqueda: Date, vehiculos: Vehiculos[], reservas: Reserva[]): number
}

class GeneradorReporte implements IGeneradorDeReporte{}

class Disponible implements IEstadoVehiculo
class En_Alquiler implements IEstadoVehiculo{
    + estaAlquilado : boolean
}
class En_Mantenimiento implements IEstadoVehiculo{
    + estaEnMantenimiento : boolean
}
class Necesita_Limpieza implements IEstadoVehiculo

abstract class Vehiculo {
    # matricula : string
    # tarifaBase : number
    # kilometraje : number
    # cargoExtra : number
    # estadoVehiculo : IEstadoVehiculo
    # kmUltimoMantenimiento : number
    # cantViajes : number
    # fechaUltimoMantenimiento: Date
    # condicionesMantenimiento: INecesitaMantenimiento[]
    # costoTotalMantenimiento : number
    # costoPorMantenimiento: number
    # historialMantenimientos: Map<Date, number>

    --setters y getters--

    + cambiarEstado(estado : IEstadoVehiculo) : void
    + necesitaMantenimiento() : void
    + alquilar() : void
    + devolver() : void
    + enviarAMantenimiento() : void
    + limpiar() : void
    
    + actualizarKilometraje(nuevo:number) : void
    + calcularTarifa(reserva) : number
}

class Compacto extends Vehiculo {
    + calcularTarifa(diasTotales: number, kmRecorridos: number): number{}
}

class Sedan extends Vehiculo {
    + calcularTarifa(diasTotales: number, kmRecorridos: number): number{}
}

class SUV extends Vehiculo {
    + calcularTarifa(diasTotales: number, kmRecorridos: number): number{}
}

class Cliente {
    - static idBase: number = 1
    - idCliente: number
    - nombre: string
    - apellido: string
    - reserva: Reserva
    - readonly: SistemaDriveHub
    
    ----setters y getters ----

    + solicitarReserva(vehiculo: Vehiculo, fechaInicio: Date, fechaFin: Date): void
    + manejar(kilometros: number, dia: Date): void
    
}

class Reserva {
    - static idBase : number
    - idReserva: number
    - vehiculo: Vehiculo
    - cliente: Cliente
    - fechaInicio: Date
    - fechaFin: Date
    - kmInicial: number
    - kmRecorridos: number
    - temporada : ITemporada

    ----setters y getters ----

    + registrarUsoVehiculo(kilometros: number): void
    
}



class SistemaDriveHub {
    - vehiculos: Vehiculo[]
    - clientes: Cliente[]
    - reservas: Reserva[]
    - mantenimiento: Mantenimiento[] 
    - generadorReporte : IGeneradorDeReporte
    - rentabilidadVehiculos : Map<Vehiculo, number>   
    
    ---setters y getters-----

    + crearReserva(cliente: Cliente, vehiculo: Vehiculo, fechaInicio: Date, fechaFin: Date)   
    + calcularTarifaFinal(reserva : Reserva) : number
    + asignarRentabilidad (vehiculo: Vehiculo, tarifaFinal: number)
    + reporteVehiculosOcupados(fechaBusqueda : Date) : number)
    + reporteVehiculoMasAlquilado(fechaInicio: Date, fechaFin: Date): Vehiculo
    + reporteVehiculoMenosAlquilado(fechaInicio: Date, fechaFin: Date): Vehiculo
    + reporteVehiculoMasRentable() : Vehiculo
    + reporteVehiculoMenosRentable() : Vehiculo
    + asignarMantenimiento(vehiculo: Vehiculo, fecha: Date, costo: number)) 

}

class EstadosFactory {
    + static crearEstadoDisponible(vehiculo: Vehiculo) : Disponible
    + static crearEstadoEnAlquiler(vehiculo: Vehiculo) : en_Alquiler
    + static crearEstadoEnMantenimiento(vehiculo: Vehiculo) : en_Mantenimiento
    + static crearEstadoNecesitaLimpieza(vehiculo: Vehiculo) : necesita_Limpieza
}

'notas
' note left of SistemaDriveHub::crearReserva
'     Este metodo deberia chequear que el vehiculo este disponible antes de crear la reserva.
' end note

' note left of SistemaDriveHub::asignarMantenimiento
'     Este metodo deberia llamar a vehiculo.setEstado() y actualizarlo.
' end note


SistemaDriveHub *-- Vehiculo
SistemaDriveHub *-- Cliente
SistemaDriveHub *-- Reserva
Vehiculo *-- IEstadoVehiculo
Vehiculo *-- INecesitaMantenimiento
Reserva *-- ITemporada

Reserva *-r- Cliente
Reserva *-l- Vehiculo

@enduml