@startuml DriveHub

' El diagrama de clases es orientativo, podra sufrir cambios a medida que avance el proyecto.

title Diagrama de Clases - DriveHub


interface ITemporada{
    calculoPorTemporada(sistema: SistemaDriveHub): number; 
}

class GestorTemporada {
    + asignarTemporadaAlta(): Temporada_Alta
    + asignarTemporadaMedia(): Temporada_Media
    + asignarTemporadaBaja(): Temporada_Baja
}

class Temporada_Alta implements ITemporada
class Temporada_Baja implements ITemporada
class Temporada_Media implements ITemporada     

interface INecesitaMantenimiento{
    + necesitaMantenimiento():boolean
}

class cantViajes implements INecesitaMantenimiento
class kilometrosParaMantenimiento implements INecesitaMantenimiento
class ultimoMantenimeinto implements INecesitaMantenimiento

interface IEstadoVehiculo {
    + asignarAlquiler() : void
    + asignarDisponible() : void
    + asignarMantenimiento() : void
    + asignarLimpieza() : void

    + puedeAlquilar() : boolean
    + estaEnMantenimiento() : boolean 
    + evaluarMantenimiento() : void
}

interface IGeneradorDeReporte {
    + vehiculoMasAlquilado(fechaInicio: Date, fechaFin: Date, reserva: Reserva[]): Vehiculo
    + vehiculoMenosAlquilado(fechaInicio: Date, fechaFin: Date, reserva: Reserva[]): Vehiculo
    + vehiculoMasRentable(vehiculos: Map<Vehiculo, number>): Vehiculo
    + vehiculoMenosRentable(vehiculos: Map<Vehiculo, number>): Vehiculo
    + vehiculosOcupados(fechaBusqueda: Date, vehiculos: Vehiculos[], reservas: Reserva[]): number
}

class GeneradorReporte implements IGeneradorDeReporte{}

class Disponible implements IEstadoVehiculo
class En_Alquiler implements IEstadoVehiculo{
    + estaEnMantenimiento : boolean
}
class En_Mantenimiento implements IEstadoVehiculo
class Necesita_Limpieza implements IEstadoVehiculo

abstract class Vehiculo {
    # matricula : string
    # tarifaBase : number
    # kilometraje : number
    # cargoExtra : number
    # estadoVehiculo : IEstadoVehiculo
    # kmUltimoMantenimiento : number
    # cantViajes : number
    # fechaUltimoMantenimiento: Date
    # costoTotalMantenimiento : number
    # costoPorMantenimiento: number
    # historialMantenimientos: Map<Date, number>

    --setters y getters--

    +actualizarInfoMantenimiento(nuevi:number):void
    +cambiarEstado (estado: IEstadoVehiculo): void
    +asignarAlquiler(): void
    +asignarDisponible(): void
    +asignarMantenimiento(): void
    +asignarLimpieza(): void
    +calcularTarifa (reserva: Reserva): number
    +puedeAlquilar(): boolean
    +actualizarInfoMantenimiento(): void

}

class Compacto extends Vehiculo {
    + calcularTarifa(diasTotales: number, kmRecorridos: number): number{}
}

class Sedan extends Vehiculo {
    + calcularTarifa(diasTotales: number, kmRecorridos: number): number{}
}

class SUV extends Vehiculo {
    + calcularTarifa(diasTotales: number, kmRecorridos: number): number{}
}

class Cliente {
    - static idBase: number = 1
    - idCliente: number
    - nombre: string
    - apellido: string
    - reserva: Reserva
    - readonly: SistemaDriveHub
    
    ----setters y getters ----

    + solicitarReserva(vehiculo: Vehiculo, fechaInicio: Date, fechaFin: Date): void
    + manejar(kilometros: number, dia: Date): void
    
}

class Reserva {
    - static idBase : number
    - idReserva: number
    - vehiculo: Vehiculo
    - cliente: Cliente
    - fechaInicio: Date
    - fechaFin: Date
    - kmInicial: number
    - kmRecorridos: number
    - temporada : ITemporada

    ----setters y getters ----

    + registrarUsoVehiculo(kilometros: number): void
    
}



class SistemaDriveHub {
    - vehiculos: Vehiculo[]
    - clientes: Cliente[]
    - reservas: Reserva[]
    - generadorReporte : IGeneradorDeReporte
    - rentabilidadVehiculos : Map<Vehiculo, number>   
    
    ---setters y getters-----

    + chequearDisponibilidad(vehiculo:Vehiculo) : boolean
    + crearReserva(cliente: Cliente, vehiculo: Vehiculo, fechaInicio: Date, fechaFin: Date)   
    + calcularTarifaFinal(reserva : Reserva) : number
    + asignarRentabilidad (vehiculo: Vehiculo, tarifaFinal: number)
    + reporteVehiculosOcupados(fechaBusqueda : Date) : number)
    + reporteVehiculoMasAlquilado(fechaInicio: Date, fechaFin: Date): Vehiculo
    + reporteVehiculoMenosAlquilado(fechaInicio: Date, fechaFin: Date): Vehiculo
    + reporteVehiculoMasRentable() : Vehiculo
    + reporteVehiculoMenosRentable() : Vehiculo

}


'notas
' note left of SistemaDriveHub::crearReserva
'     Este metodo deberia chequear que el vehiculo este disponible antes de crear la reserva.
' end note

' note left of SistemaDriveHub::asignarMantenimiento
'     Este metodo deberia llamar a vehiculo.setEstado() y actualizarlo.
' end note


SistemaDriveHub *-- Vehiculo
SistemaDriveHub *-- Cliente
SistemaDriveHub *-- Reserva
Vehiculo *-- IEstadoVehiculo
Vehiculo *-- INecesitaMantenimiento
Reserva *-- ITemporada

Reserva *-r- Cliente
Reserva *-l- Vehiculo

@enduml